// Copyright (c) 2024 Lemonade Nexus. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "flutter_generated_plugin_registrant.h"

#include <flutter_plugins.h>

void RegisterPlugins(flutter::PluginRegistry* registry) {
  // This file is generated by Flutter tooling.
  // Plugins will be registered here automatically.
}
