/// @title Generated Mocks
/// @description Generated mock classes using mockito.
///
/// This file is auto-generated by build_runner.
/// Run: flutter pub run build_runner build --delete-conflicting-outputs

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:lemonade_nexus/src/sdk/lemonade_nexus_sdk.dart' as _i2;
import 'package:lemonade_nexus/src/sdk/ffi_bindings.dart' as _i3;
import 'package:lemonade_nexus/src/state/app_state.dart' as _i4;
import 'package:lemonade_nexus/src/state/providers.dart' as _i5;

// ignore_for_file: type=lint
class _FakeLemonadeNexusSdk_0 extends _i1.SmartFake implements _i2.LemonadeNexusSdk {
  _FakeLemonadeNexusSdk_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLemonadeNexusFfi_1 extends _i1.SmartFake implements _i3.LemonadeNexusFfi {
  _FakeLemonadeNexusFfi_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppNotifier_2 extends _i1.SmartFake implements _i4.AppNotifier {
  _FakeAppNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LemonadeNexusSdk].
///
/// Generated by:
/// ```dart
/// @GenerateMocks([LemonadeNexusSdk])
/// ```
class MockLemonadeNexusSdk extends _i1.Mock implements _i2.LemonadeNexusSdk {}

/// A class which mocks [LemonadeNexusFfi].
///
/// Generated by:
/// ```dart
/// @GenerateMocks([LemonadeNexusFfi])
/// ```
class MockLemonadeNexusFfi extends _i1.Mock implements _i3.LemonadeNexusFfi {}

/// A class which mocks [AppNotifier].
///
/// Generated by:
/// ```dart
/// @GenerateMocks([AppNotifier])
/// ```
class MockAppNotifier extends _i1.Mock implements _i4.AppNotifier {}

/// A class which mocks [AuthService].
///
/// Generated by:
/// ```dart
/// @GenerateMocks([AuthService])
/// ```
class MockAuthService extends _i1.Mock implements _i5.AuthService {}

/// A class which mocks [TunnelService].
///
/// Generated by:
/// ```dart
/// @GenerateMocks([TunnelService])
/// ```
class MockTunnelService extends _i1.Mock implements _i5.TunnelService {}

/// A class which mocks [DiscoveryService].
///
/// Generated by:
/// ```dart
/// @GenerateMocks([DiscoveryService])
/// ```
class MockDiscoveryService extends _i1.Mock implements _i5.DiscoveryService {}

/// A class which mocks [TreeService].
///
/// Generated by:
/// ```dart
/// @GenerateMocks([TreeService])
/// ```
class MockTreeService extends _i1.Mock implements _i5.TreeService {}
