title: Lemonade-Nexus
description: Self-hosted userspace mesh VPN with encrypted peer-to-peer connections, cryptographic identity, and an attestation-based security protocol
theme: jekyll-theme-cayman
baseurl: "/lemonade-nexus"
url: "https://lemonade-sdk.github.io"

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
